APT::FTPArchive::Release {
  Origin "KebianOS";
  Label "KebianOS";
  Suite "stable";
  Codename "stable";
  Architectures "amd64";
  Components "main";
  Description "Repositorio APT de KebianOS";
};
